config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("lexpy.users.urls", namespace="users"),),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

lexpy/users/urls.py
from django.urls import path

from lexpy.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lexpy/users/models.py
from datetime import date

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


def user_directory_path(instance, filename):
    #file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.username, filename)


class User(AbstractUser):
    EXPERIENCE_BEGINNER = 'B'
    EXPERIENCE_BEGINT = 'BI'
    EXPERIENCE_INTERMEDIATE = 'I'
    EXPERIENCE_INTERVANCED = 'IA'
    EXPERIENCE_ADVANCED = 'A'
    DOMAIN_WEB_DEVELOPMENT = 'WD'
    DOMAIN_SCIENTIFIC_AND_NUMERIC = 'SN'
    DOMAIN_EDUCATION = 'E'
    DOMAIN_DESKTOP_GUIS = 'DG'
    DOMAIN_GAME_DEVELOPMENT = 'GD'
    DOMAIN_SOFTWARE_DEVELOPMENT = 'SD'
    DOMAIN_SCRIPTING = 'S'

    EXPERIENCE_CHOICES = (
        (EXPERIENCE_BEGINNER, 'Beginner'),
        (EXPERIENCE_BEGINT, 'Beginner to Intermediate'),
        (EXPERIENCE_INTERMEDIATE, 'Intermediate'),
        (EXPERIENCE_INTERVANCED, 'Intermediate to Advanced'),
        (EXPERIENCE_ADVANCED, 'Advanced / Professional'),
        )

    DOMAIN_CHOICES = (
        (DOMAIN_WEB_DEVELOPMENT, "Web Applications"),
        (DOMAIN_SCIENTIFIC_AND_NUMERIC, "Scientific or Numeric Applications"),
        (DOMAIN_EDUCATION, "Education"),
        (DOMAIN_DESKTOP_GUIS, "Desktop Software (GUI's)"),
        (DOMAIN_GAME_DEVELOPMENT, "Game Development"),
        (DOMAIN_SOFTWARE_DEVELOPMENT, "Support Software"),
        (DOMAIN_SCRIPTING, "Scripting"),
        )

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    photo = models.ImageField(upload_to=user_directory_path,
            blank=True,
            width_field="width_field",
            height_field="height_field")
    height_field = models.IntegerField(default=0, blank= True, null=True)
    width_field = models.IntegerField(default=0, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True)
    experience = models.CharField(max_length=2, choices=EXPERIENCE_CHOICES, blank=True, null=True)
    domain = models.CharField(max_length=2, choices=DOMAIN_CHOICES, blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

lexpy/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

lexpy/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .forms import UserChangeForm

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    fields = ["name", "photo", "city", "experience", "domain", "bio"]
    slug_field = "username"
    slug_url_kwarg = "username"

user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name", "photo", "city", "experience", "domain", "bio"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def form_valid(self, form):
        print(form.instance)
        return super(UserUpdateView, self).form_valid(form)

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

user_redirect_view = UserRedirectView.as_view()

lexpy/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

lexpy/templates/base.html
{% load static %}
{% load i18n compress%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}LexPy{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="Lexpy is a group of python beginners, enthusiasts, and professionals who enjoy meeting and discussing various python related topics on a monthly basis.">
    <meta name="author" content="Jim Wombles">
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    {% block css %}
    <!-- Third-party CSS libraries go here -->
    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock css %}
    <!-- Custom styles for this template -->
    {# <link href="jumbotron.css" rel="stylesheet"> #}
  </head>

  <body>

    {% include 'base/navbar.html' %}

    {% if messages %}
      {% for message in messages %}
        <div class="container alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}></div>
      {% endfor %}
    {% endif %}

    <main role="main">
      {% block content %}
        <p>You are viewing the base template text</p>
      {% endblock content %}
    </main>

    {% block modal %}{% endblock modal %}

    {% block footer %}
      <footer class="footer">
        <div class="container">
          {% now "Y" as current_year %}
          <span class="text-muted">{% blocktrans %}&copy; Lexpy {{ current_year }}{% endblocktrans %}</span>
        </div>
      </footer>
    {% endblock footer %}

    {% block javascript %}
      <!-- Vendor dependencies bundled as one file-->
      {% compress js %}
        <script src="{% static 'js/vendors.js' %}"></script>
      {% endcompress %}
      <!-- place project specific Javascript in this file -->
      {% compress js %}
        <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}
    {% endblock javascript %}

  </body>
</html>

lexpy/templates/base/navbar.html
{% load i18n %}

{% url 'home' as home_url %}
{% url 'events' as meetups_url %}
{% url 'about' as about_url %}
{% url 'resources' as resources_url %}
{% url 'users:detail' request.user.username as profile_url %}
{% url 'account_logout' as logout_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_login' as login_url %}


<nav class="container navbar navbar-expand-md navbar-dark fixed-top bg-gradient-success">

  <a class="navbar-brand" href="{% url 'home' %}">LexPy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">

    <ul class="navbar-nav mr-auto">

      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link" href="{% url 'about' %}">{% trans "About " %}<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item {% if request.path == meetups_url %}active{% endif %}">
        <a class="nav-link" href="#' %}">{% trans "Events " %}<span class="sr-only">(current)</span></a>
      </li>

    {% if request.user.is_authenticated %}

        <li class="nav-item {% if request.path == resources_url %}active{% endif %}">
          <a class="nav-link" href="#">{% trans "Resources " %}</a>
        </li>
        <li class="nav-item {% if request.path == profile_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
        </li>
        <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
        </li>

    {% else %}

        <li class="nav-item {% if request.path == signup_url %}active{% endif %}">
          <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
        </li>
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
        </li>

    {% endif %}
    </ul>
  </div>
</nav>

lexpy/templates/pages/about.html
{% extends "base.html" %}
{% block content %}

{% endblock content %}

lexpy/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->

    <div class="jumbotron container mt-3">
      <!-- <img src="/static/images/luca-tescari-1508486-unsplash.jpg" class="img-fluid" alt="Responsive image"> -->
       <h1 class="display-3">LexPy</h1>
        <p>Lexpy is a Lexington, Ky based group open to anyone interested in the python programming language.  We have monthly meetups that range from topical presentations to working groups, hackathons and much more!</p>
        <p>Register below to join and stay informed of upcoming lexpy meetups!</p>
        <p><a class="btn btn-primary btn-lg" href="{% url 'account_signup' %}" role="button"> &raquo; Join Lexpy</a></p>

    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Web Development</h2>
          <p>Python offers a wide range of choices for web development, from writing basic Common Gateway Interface scripts using the CGI module, to popular MVC frameworks like Django, Flask, and TurboGears.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>GUI Development</h2>
          <p>Python can be used for creating Graphical User Interface Programs.  The TkInter development library is included with most binary distributions of Python and there are many other thrid party options available like PyGObject, PyQt, PySide, Kivy, and wxPython.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Scientific and Numeric</h2>
          <p>Python is widely used in scientific and numeric computing.  A Data Scientist can combine statistical and machine learning techniques with Python programming to analyze and interpret complex data.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Software Development</h2>
          <p>The Tk GUI development library is included with most binary distributions for Python.  In addition, there are many other popular third-party GUI libraries like PyQt, Kivvy, and wxPython.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
         <div class="col-md-4">
          <h2>System Administration</h2>
          <p>Ansible, Salt, OpenStack.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
    </div>
{% endblock content %}


Web Development: Django, Pyramid, Bottle, Tornado, Flask, web2py
GUI Development: tkInter, PyGObject, PyQt, PySide, Kivy, wxPython
Scientific and Numeric: SciPy, Pandas, IPython
Software Development: Buildbot, Trac, Roundup
System Administration: Ansible, Salt, OpenStack

lexpy/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
    {% if object.name %}
      <h2>{{ object.name }}</h2>
    {% else %}
      <h2>{{ object.username }}</h2>
    {% endif %}

    {% if object == request.user %}
    <!-- Action buttons -->
    <div class="row">
      <div class="col-sm-12">
        <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Edit Profile</a>
        <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">Edit E-Mail</a>
        <!-- Your Stuff: Custom user template urls -->
      </div>
    </div>
    <!-- End Action buttons -->
    {% endif %}
    {% if user.photo %}
      <img class ="mr-3" src="{{ user.photo.url }}" width="300" alt="Profile Image">
    {% endif %}
    {% if object.get_domain_display %}
      <p>Python Interest:  {{ object.get_domain_display }}</p>
    {% endif %}
    {% if object.get_experience_display %}
      <p>Python Experience:  {{ object.get_experience_display }}</p>
    {% endif %}
    {% if object.city %}
      <p>City:  {{ object.city }}</p>
    {% endif %}
    {% if object.bio %}
      <p>Bio:  {{ object.bio }}</p>
    {% endif %}
    </div>
  </div>

</div>
{% endblock content %}

lexpy/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<div class="container">
  <h1>{{ user.username }}</h1>
  <form enctype="multipart/form-data" class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

lexpy/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}LexPy Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Members</h2>
  {% for user in user_list %}
    <ul class="list-unstyled">
      <li class="media">
        {% if user.photo %}
          <img class ="mr-3" src="{{ user.photo.url }}" width="150" alt="Profile Image">
        {% else %}
          <img class ="mr-3" src="https://placekitten.com/150/150" alt="Cat Image">
        {% endif %}
        <div class="media-body">
          <a href="{% url 'users:detail' user.username %}">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
          {% if user.bio %}
          {{ user.bio }}
          {% endif %}
        </div>
      </li>
    </ul>
  {% endfor %}
</div>
{% endblock content %}